INSERT INTO warehouse.FactSupplierDelivery
SELECT Num, 
ABS(CHECKSUM(NEWID())) % 100 + 1,
ABS(CHECKSUM(NEWID())) % 500 + 1,
DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 500, GETDATE()),
DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 500, GETDATE()) + ABS(CHECKSUM(NEWID())) % 7,
ABS(CHECKSUM(NEWID())) % 5000 + 100
FROM dbo.Numbers
WHERE Num <= 15000;