INSERT INTO warehouse.FactInventory
SELECT Num, (
SELECT TOP 1 DateKey
FROM warehouse.DimDate ORDER BY NEWID()),
ABS(CHECKSUM(NEWID())) % 500 + 1,
ABS(CHECKSUM(NEWID())) % 5 + 1,
ABS(CHECKSUM(NEWID())) % 10000,
ABS(CHECKSUM(NEWID())) % 500
FROM dbo.Numbers
WHERE Num <= 20000;